Repository tkeel-io/console, pull requests merged in 2023-01, with the labels that each got.

#755 feat: replace AceEditor to Prism in device detail RawDataPanel
  packages/tkeel-console-plugin-tenant-devices/package.json
  packages/tkeel-console-plugin-tenant-devices/src/pages/DeviceDetail/components/DeviceDetailRightPanel/index.tsx
  packages/tkeel-console-plugin-tenant-devices/src/pages/DeviceDetail/components/RawData/CustomSelect.tsx
  packages/tkeel-console-plugin-tenant-devices/src/pages/DeviceDetail/components/RawData/index.tsx
  packages/tkeel-console-utils/src/utils/raw-data/index.ts
  yarn.lock
Labels: lgtm, approved, ok-to-test, size/L

#756 fix: data query zero error
  packages/tkeel-console-plugin-tenant-data-query/src/pages/Detail/components/DataTable/index.tsx
  packages/tkeel-console-plugin-tenant-data-query/src/pages/Detail/index.tsx
Labels: lgtm, size/XS

#757 fix: type error
  packages/tkeel-console-plugin-tenant-data-query/src/pages/Detail/index.tsx
Labels: lgtm, approved, ok-to-test

#758 fix: type error
  packages/tkeel-console-plugin-tenant-data-query/src/pages/Detail/index.tsx
Labels: size/XS
